version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=martin
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=api-db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=martin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=pass
    ports:
      - "5050:80"

volumes:
  postgres:
